version: '3.8'

services:
  frontend:
    image: node:latest
    container_name: bebanova-landing
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules  # Evita conflictos con node_modules local
    ports:
      - "3000:3000"
    command: ["sh", "-c", "npm install && npm run dev"]
    environment:
      - NODE_ENV=development